# Generated by Django 2.0 on 2018-01-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='owner',
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
