# Generated by Django 2.0.1 on 2018-01-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180102_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
