# Generated by Django 2.0.1 on 2018-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_books_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.FileField(null=True, upload_to='static/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='books',
            name='owner_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='owner_review',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
