# Generated by Django 2.0.1 on 2018-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180103_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(default='static/images/no-img.png', upload_to='static/images/'),
        ),
    ]
