# Generated by Django 2.0.1 on 2018-01-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20180104_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='owner_review',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
