# Generated by Django 2.0.1 on 2018-01-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20180104_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
