# Generated by Django 2.0.1 on 2018-01-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_books_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='short_description',
        ),
    ]
