# Generated by Django 2.0.1 on 2018-01-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20180104_0019'),
        ('homepage', '0010_remove_books_short_description'),
    ]

    operations = [
    ]
