# Generated by Django 2.0.1 on 2018-01-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_merge_20180104_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='owner_review',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
